// One-time setup for the Render Postgres instance ("LA carte"):
//   1. creates the `athena` database (if missing),
//   2. generates a JWT secret and writes server/.env.
//
// Usage (from server/):
//   $env:ADMIN_DATABASE_URL='postgresql://.../hopmeds_greenfield'
//   $env:DEEPSEEK_API_KEY='sk-...'
//   node scripts/setup-db.js
//
// ADMIN_DATABASE_URL must point at an existing database on the instance
// (any database; it is only used to run CREATE DATABASE).

import crypto from 'node:crypto';
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

const here = path.dirname(fileURLToPath(import.meta.url));

const adminUrl = process.env.ADMIN_DATABASE_URL;
if (!adminUrl) {
  console.error('ADMIN_DATABASE_URL is required (connection string of any existing database on the instance).');
  process.exit(1);
}

const DB_NAME = 'athena';
const ssl = adminUrl.includes('.render.com') ? { rejectUnauthorized: false } : undefined;
const client = new pg.Client({ connectionString: adminUrl, ssl });

await client.connect();

const me = await client.query('select current_user as user, rolsuper, rolcreatedb from pg_roles where rolname = current_user');
console.log('connected as:', me.rows[0]);

const existing = await client.query('select 1 from pg_database where datname = $1', [DB_NAME]);
if (existing.rowCount > 0) {
  console.log(`database "${DB_NAME}" already exists — leaving it untouched.`);
} else {
  await client.query(`create database ${DB_NAME}`);
  console.log(`✓ created database "${DB_NAME}"`);
}

await client.end();

// ── write server/.env ────────────────────────────────────────────────────────

const url = new URL(adminUrl);
url.pathname = `/${DB_NAME}`;

const jwtSecret = crypto.randomBytes(48).toString('hex');
const deepseekKey = process.env.DEEPSEEK_API_KEY ?? '';

const envFile = [
  '# Athena API — local development environment (generated by scripts/setup-db.js).',
  '# Never commit this file.',
  '',
  `DATABASE_URL=${url.toString()}`,
  `JWT_SECRET=${jwtSecret}`,
  '',
  `DEEPSEEK_API_KEY=${deepseekKey}`,
  'DEEPSEEK_MODEL=deepseek-flash',
  'DEEPSEEK_VERIFY_MODEL=deepseek-flash',
  '',
].join('\n');

const envPath = path.join(here, '..', '.env');
writeFileSync(envPath, envFile, 'utf8');
console.log(`✓ wrote ${envPath}`);
console.log(`  DATABASE_URL host: ${url.hostname} (database: ${DB_NAME})`);
console.log(`  DEEPSEEK_API_KEY: ${deepseekKey ? 'set' : 'MISSING — add it to server/.env'}`);
